language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm install

before_deploy:
  - npm run start
  - npm run lint

script:
- zip -r trailr.zip build
- mkdir -p trailr_deploy
- mv trailr.zip trailr_deploy/trailrapp.zip