language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm install

before_deploy:
  - npm run start
  # - npm run lint

script:
  - zip -r trailrapp.zip build
