name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

  jobs:
    build:
      name: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build React
          run: npm run build-react
          run: npm run start
          env: 
            DEFAULT_BRANCH: dev